# Use an official Node.js runtime as the base image
FROM node:22

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages specified in package.json
RUN npm install
COPY ./seed.sh /seed.sh
RUN chmod +x /seed.sh

# Make port 80 available to the world outside this container
EXPOSE 3000

# Run the app when the container launches
ENTRYPOINT ["/seed.sh"]