version: '3.9'
services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: zenmaem
    volumes:
      - db_data:/var/lib/mysql
  backend:
    image: backend
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=zay
  frontend: 
    image: frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
